# Generated by Django 4.0.6 on 2022-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=25)),
                ('ModelName', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=225)),
            ],
        ),
    ]
